-- ============================================================
-- TUGAS TIM (D2 / UTS item 1.2–1.3) — dimensi entitas utama
-- Ganti nama berkas ini dengan entitasmu: 20_dim_mahasiswa.sql | 20_dim_product.sql | 20_dim_wilayah.sql
-- Ganti pula nama tabelnya. Yang WAJIB ada:
--   * surrogate key  : <entitas>_sk  (INTEGER, hasil row_number() — bukan ID dari sumber)
--   * natural key    : ID bisnis dari sumber (nim | product_id | kode wilayah) disimpan, tapi bukan PK
--   * SCD type       : satu tipe per dimensi + alasan satu baris
--   * Type 2         : valid_from, valid_to, is_current
-- ============================================================

-- CATATAN: Untuk Kelompok 3 (T2 POS UMKM, slice k8), dimensi entitas utama
-- sudah diimplementasikan di: 20_dim_product.sql (SCD Type 2, harga_berlaku_dari)
-- File ini tidak dipakai — digantikan oleh implementasi yang lebih spesifik di atas.
